---
Name: adler-brillen.de
---
SilverStripe\Core\Manifest\ModuleManifest:
  project: app
BetterBrief\GoogleMapField:
  default_options:
    api_key: ''

SilverStripe\Core\Injector\Injector:
  LogFileHandler:
    class: Monolog\Handler\StreamHandler
    constructor:
      - "../silverstripe.log"
      - "info"